import React, { useReducer } from 'react';
import Head from 'next/head';
import { ProductsContext } from '../features/Products/products-context';
import {
  reducer as productsReducer,
  initialState,
} from '../features/Products/products-reducer';
import Home from '../features/Home';

export default function HomeContainer() {
  const [state, dispatch] = useReducer(productsReducer, initialState);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ProductsContext.Provider value={[state, dispatch]}>
        <Home />
      </ProductsContext.Provider>
    </>
  );
}
